import type { PaletteColorFinish } from "./models.js";

export interface MardColorDefinition {
  code: string;
  hex: string;
  finish: PaletteColorFinish;
}

/**
 * Third-party, non-official screen-reference RGB values from
 * maxcleme/beadcolors, pinned to the commit recorded below. Authoritative
 * manufacturer verification is still pending; physical beads, lighting and
 * displays can differ, while codes remain the stable project identity.
 */
export const MARD_SOURCE = {
  name: "maxcleme/beadcolors MARD 291-color fixed dataset (non-official reference)",
  url: "https://github.com/maxcleme/beadcolors/blob/f97ff4283d03cef5cd7e1071a86f5892e0c0c61b/raw/mard.csv",
  revision: "f97ff4283d03cef5cd7e1071a86f5892e0c0c61b",
  license: "MIT; third-party non-official color reference",
} as const;

export const MARD_291_COLORS: readonly MardColorDefinition[] = [
  { code: "A1", hex: "#F9F0CD", finish: "solid" },
  { code: "A2", hex: "#FBFBD4", finish: "solid" },
  { code: "A3", hex: "#FAFC9F", finish: "solid" },
  { code: "A4", hex: "#FFE953", finish: "solid" },
  { code: "A5", hex: "#F4D738", finish: "solid" },
  { code: "A6", hex: "#FDAD49", finish: "solid" },
  { code: "A7", hex: "#FF7C2F", finish: "solid" },
  { code: "A8", hex: "#EACA49", finish: "solid" },
  { code: "A9", hex: "#FF995A", finish: "solid" },
  { code: "A10", hex: "#FF9D55", finish: "solid" },
  { code: "A11", hex: "#FFDD99", finish: "solid" },
  { code: "A12", hex: "#FCB58F", finish: "solid" },
  { code: "A13", hex: "#FFBB59", finish: "solid" },
  { code: "A14", hex: "#FF6D40", finish: "solid" },
  { code: "A15", hex: "#FDFF44", finish: "solid" },
  { code: "A16", hex: "#FEF9AE", finish: "solid" },
  { code: "A17", hex: "#FFE36E", finish: "solid" },
  { code: "A18", hex: "#FECF98", finish: "solid" },
  { code: "A19", hex: "#FD7B72", finish: "solid" },
  { code: "A20", hex: "#EFCD67", finish: "solid" },
  { code: "A21", hex: "#FFE395", finish: "solid" },
  { code: "A22", hex: "#FFF3A4", finish: "solid" },
  { code: "A23", hex: "#F3D5BF", finish: "solid" },
  { code: "A24", hex: "#FBF8C9", finish: "solid" },
  { code: "A25", hex: "#FFD67D", finish: "solid" },
  { code: "A26", hex: "#FFBB27", finish: "solid" },
  { code: "B1", hex: "#E6EE32", finish: "solid" },
  { code: "B2", hex: "#5BE419", finish: "solid" },
  { code: "B3", hex: "#7CEE9D", finish: "solid" },
  { code: "B4", hex: "#1EF942", finish: "solid" },
  { code: "B5", hex: "#00BD35", finish: "solid" },
  { code: "B6", hex: "#5AE8BA", finish: "solid" },
  { code: "B7", hex: "#03AC88", finish: "solid" },
  { code: "B8", hex: "#029D26", finish: "solid" },
  { code: "B9", hex: "#26523A", finish: "solid" },
  { code: "B10", hex: "#95D3C2", finish: "solid" },
  { code: "B11", hex: "#5D722A", finish: "solid" },
  { code: "B12", hex: "#156F40", finish: "solid" },
  { code: "B13", hex: "#D9F794", finish: "solid" },
  { code: "B14", hex: "#ADE945", finish: "solid" },
  { code: "B15", hex: "#2E5132", finish: "solid" },
  { code: "B16", hex: "#C6ED9C", finish: "solid" },
  { code: "B17", hex: "#9BB13A", finish: "solid" },
  { code: "B18", hex: "#E6EE49", finish: "solid" },
  { code: "B19", hex: "#25B88C", finish: "solid" },
  { code: "B20", hex: "#C2F0CC", finish: "solid" },
  { code: "B21", hex: "#146A6B", finish: "solid" },
  { code: "B22", hex: "#0B3C43", finish: "solid" },
  { code: "B23", hex: "#303921", finish: "solid" },
  { code: "B24", hex: "#EEFCA5", finish: "solid" },
  { code: "B25", hex: "#4E846D", finish: "solid" },
  { code: "B26", hex: "#8C7A36", finish: "solid" },
  { code: "B27", hex: "#D1DCC1", finish: "solid" },
  { code: "B28", hex: "#9EE5B9", finish: "solid" },
  { code: "B29", hex: "#C5E254", finish: "solid" },
  { code: "B30", hex: "#ECFBD0", finish: "solid" },
  { code: "B31", hex: "#C4E6B5", finish: "solid" },
  { code: "B32", hex: "#9BAB5A", finish: "solid" },
  { code: "C1", hex: "#E8FFE7", finish: "solid" },
  { code: "C2", hex: "#BCF9F6", finish: "solid" },
  { code: "C3", hex: "#A0E2FB", finish: "solid" },
  { code: "C4", hex: "#42CCFF", finish: "solid" },
  { code: "C5", hex: "#01ACEB", finish: "solid" },
  { code: "C6", hex: "#50A9F0", finish: "solid" },
  { code: "C7", hex: "#0188D3", finish: "solid" },
  { code: "C8", hex: "#1054C0", finish: "solid" },
  { code: "C9", hex: "#314BCA", finish: "solid" },
  { code: "C10", hex: "#3EBCE2", finish: "solid" },
  { code: "C11", hex: "#03B9B9", finish: "solid" },
  { code: "C12", hex: "#1C334D", finish: "solid" },
  { code: "C13", hex: "#CDE8FF", finish: "solid" },
  { code: "C14", hex: "#D5FDFF", finish: "solid" },
  { code: "C15", hex: "#23C4C6", finish: "solid" },
  { code: "C16", hex: "#1757A8", finish: "solid" },
  { code: "C17", hex: "#50D3EC", finish: "solid" },
  { code: "C18", hex: "#1C3344", finish: "solid" },
  { code: "C19", hex: "#1787A2", finish: "solid" },
  { code: "C20", hex: "#0082BE", finish: "solid" },
  { code: "C21", hex: "#BEDDFF", finish: "solid" },
  { code: "C22", hex: "#67B4BE", finish: "solid" },
  { code: "C23", hex: "#C2DCEB", finish: "solid" },
  { code: "C24", hex: "#7DC4FF", finish: "solid" },
  { code: "C25", hex: "#A9E5E5", finish: "solid" },
  { code: "C26", hex: "#2F99B3", finish: "solid" },
  { code: "C27", hex: "#EBF5FC", finish: "solid" },
  { code: "C28", hex: "#BBCFED", finish: "solid" },
  { code: "C29", hex: "#4B5BA3", finish: "solid" },
  { code: "D1", hex: "#AEB4F2", finish: "solid" },
  { code: "D2", hex: "#858EDD", finish: "solid" },
  { code: "D3", hex: "#3054AF", finish: "solid" },
  { code: "D4", hex: "#182A84", finish: "solid" },
  { code: "D5", hex: "#B843C5", finish: "solid" },
  { code: "D6", hex: "#AC7BDE", finish: "solid" },
  { code: "D7", hex: "#6E399A", finish: "solid" },
  { code: "D8", hex: "#E2D3FF", finish: "solid" },
  { code: "D9", hex: "#D5B9F8", finish: "solid" },
  { code: "D10", hex: "#361B50", finish: "solid" },
  { code: "D11", hex: "#B9BAE1", finish: "solid" },
  { code: "D12", hex: "#DE9AD4", finish: "solid" },
  { code: "D13", hex: "#B90295", finish: "solid" },
  { code: "D14", hex: "#8B279B", finish: "solid" },
  { code: "D15", hex: "#2F1F90", finish: "solid" },
  { code: "D16", hex: "#E2E1EE", finish: "solid" },
  { code: "D17", hex: "#C4D4F6", finish: "solid" },
  { code: "D18", hex: "#A45EC7", finish: "solid" },
  { code: "D19", hex: "#D8C3D7", finish: "solid" },
  { code: "D20", hex: "#9C32B2", finish: "solid" },
  { code: "D21", hex: "#9A009B", finish: "solid" },
  { code: "D22", hex: "#333995", finish: "solid" },
  { code: "D23", hex: "#EADAFC", finish: "solid" },
  { code: "D24", hex: "#7786E5", finish: "solid" },
  { code: "D25", hex: "#484FC7", finish: "solid" },
  { code: "D26", hex: "#E9C3F6", finish: "solid" },
  { code: "E1", hex: "#FDD3CC", finish: "solid" },
  { code: "E2", hex: "#FECDDF", finish: "solid" },
  { code: "E3", hex: "#FF97C3", finish: "solid" },
  { code: "E4", hex: "#E8649E", finish: "solid" },
  { code: "E5", hex: "#F551A2", finish: "solid" },
  { code: "E6", hex: "#FF346B", finish: "solid" },
  { code: "E7", hex: "#C63578", finish: "solid" },
  { code: "E8", hex: "#FFDBE9", finish: "solid" },
  { code: "E9", hex: "#E970CC", finish: "solid" },
  { code: "E10", hex: "#D33893", finish: "solid" },
  { code: "E11", hex: "#FCDDD2", finish: "solid" },
  { code: "E12", hex: "#FFA1C5", finish: "solid" },
  { code: "E13", hex: "#B6006D", finish: "solid" },
  { code: "E14", hex: "#FFD1BA", finish: "solid" },
  { code: "E15", hex: "#F2CFD0", finish: "solid" },
  { code: "E16", hex: "#FFECDE", finish: "solid" },
  { code: "E17", hex: "#FFE2EA", finish: "solid" },
  { code: "E18", hex: "#FFC9D6", finish: "solid" },
  { code: "E19", hex: "#FFD2E7", finish: "solid" },
  { code: "E20", hex: "#D8C7D1", finish: "solid" },
  { code: "E21", hex: "#BD9DA1", finish: "solid" },
  { code: "E22", hex: "#CC78A7", finish: "solid" },
  { code: "E23", hex: "#937A8D", finish: "solid" },
  { code: "E24", hex: "#F6E4F9", finish: "solid" },
  { code: "F1", hex: "#FD957B", finish: "solid" },
  { code: "F2", hex: "#FC3D45", finish: "solid" },
  { code: "F3", hex: "#F74941", finish: "solid" },
  { code: "F4", hex: "#FC283C", finish: "solid" },
  { code: "F5", hex: "#D80127", finish: "solid" },
  { code: "F6", hex: "#B0443D", finish: "solid" },
  { code: "F7", hex: "#971937", finish: "solid" },
  { code: "F8", hex: "#BC0127", finish: "solid" },
  { code: "F9", hex: "#E2677A", finish: "solid" },
  { code: "F10", hex: "#A74D22", finish: "solid" },
  { code: "F11", hex: "#6F201F", finish: "solid" },
  { code: "F12", hex: "#FD4D6A", finish: "solid" },
  { code: "F13", hex: "#DD422F", finish: "solid" },
  { code: "F14", hex: "#FFA9AD", finish: "solid" },
  { code: "F15", hex: "#C80020", finish: "solid" },
  { code: "F16", hex: "#FFD9C8", finish: "solid" },
  { code: "F17", hex: "#F79B71", finish: "solid" },
  { code: "F18", hex: "#D37C46", finish: "solid" },
  { code: "F19", hex: "#C1444A", finish: "solid" },
  { code: "F20", hex: "#CD9391", finish: "solid" },
  { code: "F21", hex: "#F4B1B4", finish: "solid" },
  { code: "F22", hex: "#FFD0CB", finish: "solid" },
  { code: "F23", hex: "#F57E66", finish: "solid" },
  { code: "F24", hex: "#FCC1C4", finish: "solid" },
  { code: "F25", hex: "#E54B4F", finish: "solid" },
  { code: "G1", hex: "#FFE2CE", finish: "solid" },
  { code: "G2", hex: "#FFCAAA", finish: "solid" },
  { code: "G3", hex: "#F4C3A5", finish: "solid" },
  { code: "G4", hex: "#E1B383", finish: "solid" },
  { code: "G5", hex: "#ED9435", finish: "solid" },
  { code: "G6", hex: "#F59734", finish: "solid" },
  { code: "G7", hex: "#9D5B3E", finish: "solid" },
  { code: "G8", hex: "#592A21", finish: "solid" },
  { code: "G9", hex: "#E6B483", finish: "solid" },
  { code: "G10", hex: "#C88135", finish: "solid" },
  { code: "G11", hex: "#E0C593", finish: "solid" },
  { code: "G12", hex: "#EBBB83", finish: "solid" },
  { code: "G13", hex: "#B7714A", finish: "solid" },
  { code: "G14", hex: "#8D614C", finish: "solid" },
  { code: "G15", hex: "#FCF9E0", finish: "solid" },
  { code: "G16", hex: "#F2D9BA", finish: "solid" },
  { code: "G17", hex: "#56403C", finish: "solid" },
  { code: "G18", hex: "#FFE4CC", finish: "solid" },
  { code: "G19", hex: "#E1943A", finish: "solid" },
  { code: "G20", hex: "#A94023", finish: "solid" },
  { code: "G21", hex: "#CB8E77", finish: "solid" },
  { code: "H1", hex: "#E2E2E2", finish: "solid" },
  { code: "H2", hex: "#FFFFFF", finish: "solid" },
  { code: "H3", hex: "#B3B3B3", finish: "solid" },
  { code: "H4", hex: "#868686", finish: "solid" },
  { code: "H5", hex: "#474747", finish: "solid" },
  { code: "H6", hex: "#2C2C2C", finish: "solid" },
  { code: "H7", hex: "#000000", finish: "solid" },
  { code: "H8", hex: "#E7D6DB", finish: "solid" },
  { code: "H9", hex: "#E4E7E3", finish: "solid" },
  { code: "H10", hex: "#EEE9EA", finish: "solid" },
  { code: "H11", hex: "#CECDD5", finish: "solid" },
  { code: "H12", hex: "#FFF5ED", finish: "solid" },
  { code: "H13", hex: "#F3E1C9", finish: "solid" },
  { code: "H14", hex: "#CFD7D3", finish: "solid" },
  { code: "H15", hex: "#98A6A8", finish: "solid" },
  { code: "H16", hex: "#3B2F23", finish: "solid" },
  { code: "H17", hex: "#F1EDED", finish: "solid" },
  { code: "H18", hex: "#FFFDF0", finish: "solid" },
  { code: "H19", hex: "#F6EFE2", finish: "solid" },
  { code: "H20", hex: "#949FA3", finish: "solid" },
  { code: "H21", hex: "#F7F3E4", finish: "solid" },
  { code: "H22", hex: "#CACAD5", finish: "solid" },
  { code: "H23", hex: "#9A9D94", finish: "solid" },
  { code: "M1", hex: "#BCC6B8", finish: "solid" },
  { code: "M2", hex: "#8AA385", finish: "solid" },
  { code: "M3", hex: "#697D80", finish: "solid" },
  { code: "M4", hex: "#DACEBE", finish: "solid" },
  { code: "M5", hex: "#D0CCAA", finish: "solid" },
  { code: "M6", hex: "#B0A782", finish: "solid" },
  { code: "M7", hex: "#B4A497", finish: "solid" },
  { code: "M8", hex: "#B38281", finish: "solid" },
  { code: "M9", hex: "#A58767", finish: "solid" },
  { code: "M10", hex: "#C5B1BC", finish: "solid" },
  { code: "M11", hex: "#9F7494", finish: "solid" },
  { code: "M12", hex: "#644749", finish: "solid" },
  { code: "M13", hex: "#D19066", finish: "solid" },
  { code: "M14", hex: "#C77361", finish: "solid" },
  { code: "M15", hex: "#757D7B", finish: "solid" },
  { code: "P1", hex: "#FCF8F9", finish: "pearlescent" },
  { code: "P2", hex: "#BDA9AB", finish: "pearlescent" },
  { code: "P3", hex: "#AEDDA9", finish: "pearlescent" },
  { code: "P4", hex: "#FDA49E", finish: "pearlescent" },
  { code: "P5", hex: "#EC8D3D", finish: "pearlescent" },
  { code: "P6", hex: "#60CFA8", finish: "pearlescent" },
  { code: "P7", hex: "#EB9271", finish: "pearlescent" },
  { code: "P8", hex: "#F0D958", finish: "pearlescent" },
  { code: "P9", hex: "#D9D9D9", finish: "pearlescent" },
  { code: "P10", hex: "#D5C8E9", finish: "pearlescent" },
  { code: "P11", hex: "#F3ECC8", finish: "pearlescent" },
  { code: "P12", hex: "#E6EEF1", finish: "pearlescent" },
  { code: "P13", hex: "#A9CBF1", finish: "pearlescent" },
  { code: "P14", hex: "#3177B0", finish: "pearlescent" },
  { code: "P15", hex: "#668575", finish: "pearlescent" },
  { code: "P16", hex: "#FFBE46", finish: "pearlescent" },
  { code: "P17", hex: "#FFA324", finish: "pearlescent" },
  { code: "P18", hex: "#FEB89F", finish: "pearlescent" },
  { code: "P19", hex: "#FFE0E8", finish: "pearlescent" },
  { code: "P20", hex: "#FEBECF", finish: "pearlescent" },
  { code: "P21", hex: "#ECBEC0", finish: "pearlescent" },
  { code: "P22", hex: "#E4A89E", finish: "pearlescent" },
  { code: "P23", hex: "#A56269", finish: "pearlescent" },
  { code: "Q1", hex: "#F2A5E8", finish: "thermochromic" },
  { code: "Q2", hex: "#73B29E", finish: "thermochromic" },
  { code: "Q3", hex: "#FFFF00", finish: "thermochromic" },
  { code: "Q4", hex: "#FFEBFA", finish: "thermochromic" },
  { code: "Q5", hex: "#4F5E5B", finish: "thermochromic" },
  { code: "R1", hex: "#D50E21", finish: "translucent" },
  { code: "R2", hex: "#F92E83", finish: "translucent" },
  { code: "R3", hex: "#FD8225", finish: "translucent" },
  { code: "R4", hex: "#F8EC31", finish: "translucent" },
  { code: "R5", hex: "#34C75B", finish: "translucent" },
  { code: "R6", hex: "#25B891", finish: "translucent" },
  { code: "R7", hex: "#17779D", finish: "translucent" },
  { code: "R8", hex: "#1B60C3", finish: "translucent" },
  { code: "R9", hex: "#9A56B4", finish: "translucent" },
  { code: "R10", hex: "#FFDB4D", finish: "translucent" },
  { code: "R11", hex: "#FFEBFA", finish: "translucent" },
  { code: "R12", hex: "#D8D5CE", finish: "translucent" },
  { code: "R13", hex: "#55514C", finish: "translucent" },
  { code: "R14", hex: "#9EE4DF", finish: "translucent" },
  { code: "R15", hex: "#77CEE9", finish: "translucent" },
  { code: "R16", hex: "#3DCFCA", finish: "translucent" },
  { code: "R17", hex: "#4A867A", finish: "translucent" },
  { code: "R18", hex: "#7FCD9D", finish: "translucent" },
  { code: "R19", hex: "#CDE55D", finish: "translucent" },
  { code: "R20", hex: "#E8C7B4", finish: "translucent" },
  { code: "R21", hex: "#AD6F3C", finish: "translucent" },
  { code: "R22", hex: "#6C372F", finish: "translucent" },
  { code: "R23", hex: "#FEB872", finish: "translucent" },
  { code: "R24", hex: "#F2C1C0", finish: "translucent" },
  { code: "R25", hex: "#C9675D", finish: "translucent" },
  { code: "R26", hex: "#D293BE", finish: "translucent" },
  { code: "R27", hex: "#EA8CB1", finish: "translucent" },
  { code: "R28", hex: "#9C87D6", finish: "translucent" },
  { code: "T1", hex: "#E2DFD7", finish: "transparent" },
  { code: "Y1", hex: "#FD6FB4", finish: "glow-in-the-dark" },
  { code: "Y2", hex: "#FEB481", finish: "glow-in-the-dark" },
  { code: "Y3", hex: "#D7FAA0", finish: "glow-in-the-dark" },
  { code: "Y4", hex: "#8BDBFA", finish: "glow-in-the-dark" },
  { code: "Y5", hex: "#E987EA", finish: "glow-in-the-dark" },
  { code: "ZG1", hex: "#DAABB3", finish: "photochromic" },
  { code: "ZG2", hex: "#D6AA87", finish: "photochromic" },
  { code: "ZG3", hex: "#C1BD8D", finish: "photochromic" },
  { code: "ZG4", hex: "#96869F", finish: "photochromic" },
  { code: "ZG5", hex: "#8490A6", finish: "photochromic" },
  { code: "ZG6", hex: "#94BFE2", finish: "photochromic" },
  { code: "ZG7", hex: "#E2A9D2", finish: "photochromic" },
  { code: "ZG8", hex: "#AB91C0", finish: "photochromic" },
];

export const MARD_48_CODES = [
  "A4", "A6", "A7", "A10", "A11", "A13", "B3", "B5", "B8", "B12",
  "C2", "C3", "C5", "C6", "C7", "C8", "C10", "C11", "C13", "D3",
  "D6", "D7", "D9", "D13", "D15", "D18", "D19", "D21", "E2", "E3",
  "E4", "E7", "E8", "F5", "F8", "F13", "G1", "G5", "G7", "G8",
  "G9", "G13", "H1", "H2", "H3", "H4", "H5", "H7",
] as const;

export const MARD_72_CODES = [
  "A3", "A4", "A6", "A7", "A10", "A11", "A13", "B3", "B5", "B7",
  "B8", "B10", "B12", "B14", "B17", "B18", "B19", "B20", "C2", "C3",
  "C5", "C6", "C7", "C8", "C10", "C11", "C13", "C16", "D2", "D3",
  "D6", "D7", "D8", "D9", "D11", "D12", "D13", "D14", "D15", "D16",
  "D18", "D19", "D20", "D21", "E1", "E2", "E3", "E4", "E5", "E7",
  "E8", "E12", "E13", "F5", "F7", "F8", "F10", "F13", "G1", "G2",
  "G3", "G5", "G7", "G8", "G9", "G13", "H1", "H2", "H3", "H4",
  "H5", "H7",
] as const;

const MARD_144_CODE_SET = new Set([
  ...Array.from({ length: 15 }, (_, index) => `A${index + 1}`),
  ...Array.from({ length: 8 }, (_, index) => `B${index + 1}`),
  ...Array.from({ length: 11 }, (_, index) => `B${index + 10}`),
  ...Array.from({ length: 11 }, (_, index) => `C${index + 1}`),
  ...Array.from({ length: 5 }, (_, index) => `C${index + 13}`),
  ...Array.from({ length: 3 }, (_, index) => `D${index + 1}`),
  ...Array.from({ length: 5 }, (_, index) => `D${index + 5}`),
  ...Array.from({ length: 11 }, (_, index) => `D${index + 11}`),
  ...Array.from({ length: 15 }, (_, index) => `E${index + 1}`),
  ...Array.from({ length: 14 }, (_, index) => `F${index + 1}`),
  ...Array.from({ length: 17 }, (_, index) => `G${index + 1}`),
  ...Array.from({ length: 14 }, (_, index) => `H${index + 1}`),
  ...Array.from({ length: 15 }, (_, index) => `M${index + 1}`),
]);

const MARD_221_CODE_SET = new Set(
  MARD_291_COLORS
    .map((color) => color.code)
    .filter((code) => /^(?:A|B|C|D|E|F|G|H|M)\d+$/.test(code)),
);

export const MARD_144_CODES = MARD_291_COLORS
  .map((color) => color.code)
  .filter((code) => MARD_144_CODE_SET.has(code));

export const MARD_221_CODES = MARD_291_COLORS
  .map((color) => color.code)
  .filter((code) => MARD_221_CODE_SET.has(code));

if (MARD_291_COLORS.length !== 291 || MARD_144_CODES.length !== 144 || MARD_221_CODES.length !== 221) {
  throw new Error("MARD palette dataset count mismatch");
}

